language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script: pytest

deploy:
  provider: heroku
  api_key: 7beb7d23-83d3-48fa-8835-a0ada9b0d6e1
  app: travis-demo-wou